# Site settings
language:               ""
title:                  "Lyudmil Shoshorov"
description:            "Portfolio"
google-verification:    ""

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
  - ".DS_Store"
  - "/assets/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"
  - "yarn.lock"
  - "yarn-error.log"

# Plugins
# Add plugins in the Gemfile

# Conversion
incremental:      true

destination: "_site"
keep_files: 
  - "/.git/"
  - "CNAME"


# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# Outputting
permalink:        "/blog/:year/:title/"
paginate_path:    "/blog/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]

highlighter:      rouge

collections:
  projects:
   permalink: /projects/:title/
   output: tru